obj-$(CONFIG_OPLUS_COMMON_SOFT)  +=  device_info/

#ifdef OPLUS_FEATURE_THERMAL_HORAE
obj-$(CONFIG_HORAE_THERMAL_SHELL) += thermal/
#endif /* OPLUS_FEATURE_THERMAL_HORAE */

# OPLUS Performance Optimization
obj-y += performance/
obj-y += system/
obj-y += oplus_wakelock/
obj-y += sensor/

# OPLUS Security
#obj-y  +=  oppo_healthinfo/
