# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/techpack/audio/include
ccflags-y += -I$(srctree)/techpack/audio/include/uapi

snd-soc-sia81xx-objs := sia81xx.o sia81xx_afe.o sia81xx_regmap.o sia81xx_set_vdd.o \
                         sia81xx_aux_dev_if.o sia81xx_timer_task.o \
                         sia8101_regs.o sia8108_regs.o sia8109_regs.o
obj-$(CONFIG_SND_SOC_SIA81XX) += snd-soc-sia81xx.o
