# SPDX-License-Identifier: GPL-2.0
# OPLUS Performance Optimization Drivers

obj-y += cpufreq_bouncing/
obj-$(CONFIG_OPLUS_FG_IO_OPT) += foreground_io_opt/
obj-$(CONFIG_OPLUS_FEATURE_INPUT_BOOST) += input_boost/
obj-y += iomonitor/
obj-y += lowmem_dbg/
obj-$(CONFIG_OPLUS_MEMORY_ISOLATE) += memory_isolate/
obj-$(CONFIG_OPLUS_MULTI_KSWAPD) += multi_kswapd/
obj-y += special_opt/
obj-$(CONFIG_OPLUS_FEATURE_TPD) += tpd/
obj-$(CONFIG_OPLUS_FEATURE_TPP) += tpp/
obj-$(CONFIG_OPLUS_FEATURE_UIFIRST) += uifirst/
obj-y += zwb_handle/
obj-y += healthinfo/
obj-y += im/
obj-y += memleak_detect/
obj-y += oplus_mm/
obj-y += oplus_nandswap/

# Optional modules
obj-$(CONFIG_OPLUS_GLOOM) += gloom/
obj-$(CONFIG_OPLUS_GLOOM_NEW) += gloom_new/
obj-$(CONFIG_OPLUS_ION_BOOST_POOL) += ion_boost_pool/
obj-$(CONFIG_OPLUS_MULTI_FREEAREA) += multi_freearea/
obj-$(CONFIG_OPLUS_VM_ANTI_FRAGMENT) += vm_anti_fragment/
